version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 5000:5000

  purchase:
    build:
      context: ./purchase_microservice
      dockerfile: Dockerfile
    ports:
      - 5001:5001